### ISSUE TITLE
Initial Calibration fails

### ISSUE THREAD

**Issue by Activusto** [bdunderscore/OpenVR-SpaceCalibrator#1]
Each time I start up CC,, it says Initial CC fails.
It still continues after and sometimes recalibrates, takes a bit till then.
Tad annoying.

**Comment by Activusto** [comment]
![image](https://user-images.githubusercontent.com/15093941/183235118-2831de5e-c556-4828-bb7b-e06aa1798504.png)

**Comment by bdunderscore** [comment]
This is normal, continuous calibration waits until it has enough clean data to calibrate. Try setting calibration speed to fast, and turning your head up/down and left/right once or twice.
