### ISSUE TITLE
Playspace Calibration goes to the Origin point when turning SteamVR back on

### ISSUE THREAD

**Issue by Activusto** [bdunderscore/OpenVR-SpaceCalibrator#2]
I've noticed that whenever I leave CC running, and turn steamVR back on, all my controllers and trackers are in the Origin point of the World instead of being lined up.
Disabling CC fixes it so I usually Re-enable after.

I think it could be related to the Initial Calibration not working.

**Comment by bdunderscore** [comment]
Should be fixed in r2.
