### ISSUE TITLE
Short battery life when using continuous calibration

### ISSUE THREAD

**Issue by npburns224** [bdunderscore/OpenVR-SpaceCalibrator#9]
I’m noticing that the tracker mounted to my HMD for continuous calibration is being drained significantly faster than the trackers being used for FBT. 

Is this to be expected? If so, would there be any way to reduce it?

**Comment by bdunderscore** [comment]
Spacecal doesn’t give the head tracker any special commands, so my only guess would be that the heat from the HMD is hurting battery life. Not much I can do about that I’m afraid.
